env: development
port: "8080"

db:
  host: localhost
  port: "3306"
  user: root
  password: 123456
  name: parking

jwt:
  secret: "parking"
  expires_in: 24h
  max_age: 86400

log_file_path: "E:/文件存放/parking/log/parking.log" # 添加日志文件路径配置