// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/bind-parking": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员根据用户 ID 和车位 ID 将车位绑定给指定用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "管理员将车位绑定给用户",
                "parameters": [
                    {
                        "description": "绑定车位请求体",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BindParkingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "绑定成功",
                        "schema": {
                            "$ref": "#/definitions/models.BindParkingResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "description": "管理员登录并返回 JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AdminLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回token",
                        "schema": {
                            "$ref": "#/definitions/controllers.AdminLoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "认证失败，用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "非管理员用户，无权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/parking/{parkingID}/bind-user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员根据车位 ID 查询车位绑定的用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "查询车位绑定的用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "车位 ID",
                        "name": "parkingID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "车位绑定用户信息",
                        "schema": {
                            "$ref": "#/definitions/models.ParkingBindUserResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "车位不存在",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/spots/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员根据车位ID修改车位状态（空闲/占用/故障）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "更新车位状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "车位ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateSpotStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.ParkingSpotResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回当前系统的车位总数、可用车位数、各类型车位利用率等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "获取系统统计数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.SystemStatsResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/unbind-parking": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员根据用户 ID 和车位 ID 解除车位与指定用户的绑定",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "管理员解除车位与用户的绑定",
                "parameters": [
                    {
                        "description": "解除绑定车位请求体",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UnbindParkingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解除绑定成功",
                        "schema": {
                            "$ref": "#/definitions/models.BindParkingResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "用户或车位不存在",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{userID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员根据用户 ID 查询用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "查询用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/models.UserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "注册一个新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功消息",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "用户名或邮箱已存在",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/internal/create-admin-controller": {
            "post": {
                "description": "根据传入的停车服务、报告服务和认证服务实例创建 AdminController 实例",
                "tags": [
                    "控制器初始化"
                ],
                "summary": "创建 AdminController 实例",
                "parameters": [
                    {
                        "description": "停车服务实例",
                        "name": "ps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.ParkingService"
                        }
                    },
                    {
                        "description": "报告服务实例",
                        "name": "rs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.ReportService"
                        }
                    },
                    {
                        "description": "认证服务实例",
                        "name": "as",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.AuthService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功创建 AdminController 实例",
                        "schema": {
                            "$ref": "#/definitions/controllers.AdminController"
                        }
                    }
                }
            }
        },
        "/lease": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户根据车位ID和租赁时长创建订单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lease"
                ],
                "summary": "创建租赁订单",
                "parameters": [
                    {
                        "description": "租赁信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LeaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.LeaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登录并返回 JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回token",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "认证失败，用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/owner/purchase": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户购置指定的永久车位，提交车位ID和价格信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "owner"
                ],
                "summary": "购置永久车位",
                "parameters": [
                    {
                        "description": "购置信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PurchaseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "购置成功，返回车位信息",
                        "schema": {
                            "$ref": "#/definitions/controllers.ParkingSpotResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parking/entry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "车辆入场时登记车牌号，开始计费",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking"
                ],
                "summary": "车辆入场登记",
                "parameters": [
                    {
                        "description": "入场信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.EntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "入场记录",
                        "schema": {
                            "$ref": "#/definitions/controllers.RecordResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parking/exit/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "车辆出场时结算停车费用，返回停车记录和费用信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking"
                ],
                "summary": "车辆出场结算",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "停车记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "出场结算记录",
                        "schema": {
                            "$ref": "#/definitions/controllers.RecordResponse"
                        }
                    },
                    "400": {
                        "description": "无效的ID参数",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parking/my-spots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询当前用户名下的所有车位信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking"
                ],
                "summary": "查询自己的车位",
                "responses": {
                    "200": {
                        "description": "返回用户的车位列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ParkingSpot"
                            }
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parking/rent": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户将自己的车位发布出租，需指定车位ID、出租价格及出租天数。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking"
                ],
                "summary": "出租车位",
                "parameters": [
                    {
                        "description": "出租车位请求体",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "发布成功返回租赁信息",
                        "schema": {
                            "$ref": "#/definitions/controllers.LeaseResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/parking/spots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取所有车位的详细列表，包括类型、状态和收费标准",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking"
                ],
                "summary": "获取车位列表",
                "responses": {
                    "200": {
                        "description": "返回车位列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ParkingSpot"
                            }
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "新增一个车位，指定车位类型和收费标准",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "parking"
                ],
                "summary": "创建车位",
                "parameters": [
                    {
                        "description": "车位信息",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateSpotRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功的车位信息",
                        "schema": {
                            "$ref": "#/definitions/controllers.ParkingSpotResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/daily": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据指定天数获取每日停车收入和车位使用统计，默认返回最近7天的数据。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "获取日报表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 7,
                        "description": "查询天数，默认为7天",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "日报表数据",
                        "schema": {
                            "$ref": "#/definitions/controllers.DailyReportResponse"
                        }
                    },
                    "400": {
                        "description": "无效的查询参数",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vehicles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询当前用户名下的所有车辆信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "查询自己的车辆",
                "responses": {
                    "200": {
                        "description": "返回用户的车辆列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.VehicleResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将车辆绑定到当前用户账户，支持填写车牌号、品牌及车型信息。业主绑定车辆（可绑定多个）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "绑定车辆",
                "parameters": [
                    {
                        "description": "绑定车辆请求体",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.BindVehicleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "绑定成功返回车辆信息",
                        "schema": {
                            "$ref": "#/definitions/controllers.VehicleResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vehicles/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "用户删除自己绑定的车辆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "删除车辆",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "车辆ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/controllers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "未授权访问",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "车辆不存在或无权操作",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.Config": {
            "type": "object",
            "properties": {
                "db": {
                    "type": "object",
                    "properties": {
                        "host": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        },
                        "port": {
                            "type": "string"
                        },
                        "user": {
                            "type": "string"
                        }
                    }
                },
                "env": {
                    "type": "string"
                },
                "jwt": {
                    "$ref": "#/definitions/config.JWTConfig"
                },
                "logFilePath": {
                    "description": "添加 LogFilePath 字段",
                    "type": "string"
                },
                "port": {
                    "type": "string"
                }
            }
        },
        "config.JWTConfig": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "type": "string"
                },
                "maxAge": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                }
            }
        },
        "controllers.AdminController": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "JWT Token",
                    "type": "string"
                }
            }
        },
        "controllers.AdminLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.AdminLoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "JWT Token",
                    "type": "string"
                }
            }
        },
        "controllers.BindVehicleRequest": {
            "type": "object",
            "required": [
                "license"
            ],
            "properties": {
                "brand": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "controllers.CreateSpotRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "hourly_rate": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/models.ParkingType"
                }
            }
        },
        "controllers.DailyReportResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "permanent_count": {
                    "type": "integer"
                },
                "short_term_count": {
                    "type": "integer"
                },
                "temporary_count": {
                    "type": "integer"
                },
                "total_income": {
                    "type": "number"
                }
            }
        },
        "controllers.EntryRequest": {
            "type": "object",
            "required": [
                "license"
            ],
            "properties": {
                "license": {
                    "description": "车牌号",
                    "type": "string"
                }
            }
        },
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "controllers.LeaseRequest": {
            "type": "object",
            "required": [
                "months",
                "rate",
                "spot_id"
            ],
            "properties": {
                "months": {
                    "description": "租赁月数",
                    "type": "integer",
                    "minimum": 1
                },
                "rate": {
                    "description": "每月租金",
                    "type": "number"
                },
                "spot_id": {
                    "description": "车位ID",
                    "type": "integer"
                }
            }
        },
        "controllers.LeaseResponse": {
            "type": "object",
            "properties": {
                "end_date": {
                    "description": "结束日期",
                    "type": "string"
                },
                "id": {
                    "description": "订单ID",
                    "type": "integer"
                },
                "spot_id": {
                    "description": "车位ID",
                    "type": "integer"
                },
                "start_date": {
                    "description": "起始日期（格式：YYYY-MM-DD）",
                    "type": "string"
                },
                "status": {
                    "description": "当前状态",
                    "type": "string"
                },
                "total": {
                    "description": "总金额",
                    "type": "number"
                }
            }
        },
        "controllers.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "controllers.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "JWT Token",
                    "type": "string"
                }
            }
        },
        "controllers.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "controllers.ParkingSpotResponse": {
            "type": "object",
            "properties": {
                "hourly_rate": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controllers.PurchaseRequest": {
            "type": "object",
            "required": [
                "price",
                "spot_id"
            ],
            "properties": {
                "price": {
                    "description": "购置价格",
                    "type": "number"
                },
                "spot_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.RecordResponse": {
            "type": "object",
            "properties": {
                "cost": {
                    "description": "停车费用",
                    "type": "number"
                },
                "entry_time": {
                    "description": "入场时间",
                    "type": "string"
                },
                "exit_time": {
                    "description": "出场时间",
                    "type": "string"
                },
                "id": {
                    "description": "记录ID",
                    "type": "integer"
                },
                "license": {
                    "description": "车牌号",
                    "type": "string"
                },
                "spot_id": {
                    "description": "车位ID",
                    "type": "integer"
                }
            }
        },
        "controllers.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "controllers.RentRequest": {
            "type": "object",
            "required": [
                "days",
                "rate",
                "spot_id"
            ],
            "properties": {
                "days": {
                    "type": "integer",
                    "minimum": 1
                },
                "rate": {
                    "type": "number"
                },
                "spot_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.SystemStatsResponse": {
            "type": "object",
            "properties": {
                "available_spots": {
                    "type": "integer"
                },
                "total_spots": {
                    "type": "integer"
                },
                "utilization_rates": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                }
            }
        },
        "controllers.UpdateSpotStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "notes": {
                    "description": "备注说明",
                    "type": "string"
                },
                "status": {
                    "description": "车位状态",
                    "enum": [
                        "idle",
                        "occupied",
                        "faulty"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ParkingStatus"
                        }
                    ]
                }
            }
        },
        "controllers.VehicleResponse": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_default": {
                    "type": "boolean"
                },
                "license": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                }
            }
        },
        "models.BindParkingRequest": {
            "type": "object",
            "required": [
                "parking_id",
                "user_id"
            ],
            "properties": {
                "parking_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.BindParkingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ParkingBindUserResponse": {
            "type": "object",
            "properties": {
                "parking_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ParkingSpot": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "expiresAt": {
                    "description": "过期时间，修改为 VARCHAR 类型",
                    "type": "string"
                },
                "hourlyRate": {
                    "description": "每小时费率",
                    "type": "number"
                },
                "id": {
                    "description": "车位ID",
                    "type": "integer"
                },
                "license": {
                    "description": "车牌号",
                    "type": "string"
                },
                "monthlyRate": {
                    "description": "每月费率",
                    "type": "number"
                },
                "notes": {
                    "description": "备注",
                    "type": "string"
                },
                "ownerID": {
                    "description": "业主ID",
                    "type": "integer"
                },
                "status": {
                    "description": "车位状态",
                    "type": "string"
                },
                "type": {
                    "description": "车位类型",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.ParkingStatus": {
            "type": "string",
            "enum": [
                "idle",
                "occupied",
                "faulty"
            ],
            "x-enum-varnames": [
                "Idle",
                "Occupied",
                "Faulty"
            ]
        },
        "models.ParkingType": {
            "type": "string",
            "enum": [
                "permanent",
                "short_term",
                "temporary"
            ],
            "x-enum-varnames": [
                "Permanent",
                "ShortTerm",
                "Temporary"
            ]
        },
        "models.UnbindParkingRequest": {
            "type": "object",
            "required": [
                "parking_id",
                "user_id"
            ],
            "properties": {
                "parking_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.UserInfoResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "services.AuthService": {
            "type": "object",
            "properties": {
                "cfg": {
                    "$ref": "#/definitions/config.Config"
                }
            }
        },
        "services.ParkingService": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string"
                }
            }
        },
        "services.ReportService": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "停车场管理系统 API",
	Description:      "停车场管理系统的 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
